apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-dfkb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-dfkb
    app.kubernetes.io/part-of: e2e-nodejs
  name: simple-nodejs-app-dfkb
  namespace: e2e-demos-qlrr-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: simple-nodejs-app-dfkb
    weight: null
status: {}
