apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-dfkb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-dfkb
    app.kubernetes.io/part-of: e2e-nodejs
  name: simple-nodejs-app-dfkb
  namespace: e2e-demos-qlrr-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: simple-nodejs-app-dfkb
status:
  loadBalancer: {}
